// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"database/sql"
	"time"
)

type UpwardliConsumer struct {
	ID            string    `db:"id" json:"id"`
	Pcid          string    `db:"pcid" json:"pcid"`
	ExternalID    string    `db:"external_id" json:"externalId"`
	IsActive      bool      `db:"is_active" json:"isActive"`
	KycStatus     string    `db:"kyc_status" json:"kycStatus"`
	TaxIDType     string    `db:"tax_id_type" json:"taxIdType"`
	TaxIdentifier string    `db:"tax_identifier" json:"taxIdentifier"`
	CreatedAt     time.Time `db:"created_at" json:"createdAt"`
	UpdatedAt     time.Time `db:"updated_at" json:"updatedAt"`
	Deleted       bool      `db:"deleted" json:"deleted"`
}

type UpwardliWebhook struct {
	ID          string        `db:"id" json:"id"`
	WebhookName string        `db:"webhook_name" json:"webhookName"`
	Endpoint    string        `db:"endpoint" json:"endpoint"`
	PartnerID   string        `db:"partner_id" json:"partnerId"`
	CreatedAt   time.Time     `db:"created_at" json:"createdAt"`
	UpdatedAt   time.Time     `db:"updated_at" json:"updatedAt"`
	Status      string        `db:"status" json:"status"`
	Failures    sql.NullInt32 `db:"failures" json:"failures"`
	LastFailure sql.NullTime  `db:"last_failure" json:"lastFailure"`
	Deleted     sql.NullBool  `db:"deleted" json:"deleted"`
}
