// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateUpwardliWebhook(ctx context.Context, arg CreateUpwardliWebhookParams) error
	GetAllUpwardliWebhooks(ctx context.Context) ([]GetAllUpwardliWebhooksRow, error)
	GetUpwardliWebhookById(ctx context.Context, id string) (GetUpwardliWebhookByIdRow, error)
	SoftDeleteUpwardliWebhook(ctx context.Context, id string) error
}

var _ Querier = (*Queries)(nil)
